#!/bin/bash

[[ ! -f /etc/sudoers.d/$USER ]] && echo -e "su\necho \"$USER ALL=(ALL) NOPASSWD:ALL"\" \> /etc/sudoers.d/$USER && exit 1

[[ ! -d ~/.themes/Stem ]] && mkdir ~/.themes && cp style/Stem ~/.themes -R
[[ ! -f ~/.gitconfig ]] && cp dotfiles/gitconfig ~/.gitconfig
[[ ! -f ~/.bash_aliases ]] && cp dotfiles/bash_aliases ~/.bash_aliases
cp dotfiles/sublime-settings ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
cp dotfiles/sublime-keymap ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap

for dir in Documents Music Pictures Public Templates Videos; do
  [[ -d ${dir} ]] && rmdir ${dir}
done

for dir in live-test local-temp .config/anomaly cpeople/{workspace-{andorid,go,java,js,misc,py},misc-install}; do
  [[ ! -d ${dir} ]] && mkdir -pv ~/${dir}
done

ssh-keygen -t rsa -f /home/$USER/.ssh/id_rsa -t rsa -b 4096 -q -P ""
echo -e "ssh key generated:\n"
cat /home/$USER/.ssh/id_rsa.pub
echo -e "\nadd it: https://github.com/settings/keys"

