#!/bin/bash

# remove desktop icons

xfconf-query -c xfce4-desktop -n -p "/desktop-icons/file-icons/show-filesystem" -t bool -s "false"
xfconf-query -c xfce4-desktop -n -p "/desktop-icons/file-icons/show-home" -t bool -s "false"
xfconf-query -c xfce4-desktop -n -p "/desktop-icons/file-icons/show-removable" -t bool -s "false"
xfconf-query -c xfce4-desktop -n -p "/desktop-icons/file-icons/show-trash" -t bool -s "false"
